### ISSUE TITLE
Roadmap to valet-plus 2.x

### ISSUE THREAD

**Issue by Neodork** [weprovide/valet-plus#393]
Dear Community,

The valet-plus contributors and developers from WeProvide have gotten together to improve the workflow of our beloved product. And we've compiled a list of changes we want to start working on as part of valet-plus 2.x. We think this is a step into the right direction and hope to improve the service valet-plus and contributors can offer to the community. This will cover the following subjects:

- PHP Version management
- Contributed code / Testing
- Workflow of features, hotfixes and releases.
- Brew packages upgrading to non-BC versions

**CI / CD**
Due to not having a CI/CD in place all testing is fully reliant on the developer who creates the feature/hotfix. Due to the great amount of variables and states to take in consideration this often results on code that works on one machine but breaks on another. To improve this we would like to add a CI/CD integration which checks at least the following:

- [X] Installation instructions
- [X] PSR-2 Codestyle checks
- [X] PHP switching (For 5.6, 7.0, 7.1, 7.2 and 7.3)
- [X] PHP Extension: xdebug
- [X] PHP Extension: ioncube
- [X] PHP Extension: Memcached
- [X] Memcached install and uninstall
- [ ] ... More to be added

**Contributor guidelines / Release strategy**
Valet-plus has been in v1.0.x state for a long time. All features/hotfixes get merged and the patch version gets increased to signify a new release. This creates instabilities because new features are deployed without notifying the user correctly. Therefore we're going to implement the following:

- [X] [SEMVER](https://semver.org/) strategy
- [X] [Changelog](https://keepachangelog.com/en/1.0.0/) strategy
- [X] PSR-2 Adoption
- [X] Having an issue template to support bugs and branch selection
- [ ] Moving help and questions to slack and stackoverflow
- [ ] Having an debug command to output all relevant information to a debug file for bug submissions.

As explained on the SEMVER page that will mean that:
- Non-BC changes target the MAJOR versions
- BC features target the MINOR versions
- BC hotfixes target the PATCH versions

The issue queue has been flooding with issues we're technically unable to solve or help with. The reason basically boils down to too little information for us to act on it. Therefore we're going setup an issue template which you are REQUIRED to adhere to. If you do not adhere to the template the valet-plus team will reserve the right to close your ticket without any explanation. To improve the information you can supply the valet-plus team with, we're implementing a debug command which will write configuration information to a file. The file will be required to be included in bug reports. The debug file will make it a lot easier for the valet-plus team to reproduce your exact situation.

In addition to that the issue queue will be for BUGS and FEATURES only. Any questions and small help related questions should be directed to Slack and/or Stackoverflow. Slack gives you direct contact with developers that know the most of valet-plus and stackoverflow is a great tool to reach other valet-plus users experiencing common issues like local configuration issues.

Lastly but definitely not least, that means that all remaining bugs in the queue shall be closed and tagged as 1.0.x. If the bug still persists in 2.x please feel free to reopen the ticket in the correct format. We know this is a sensitive thing to do in a community providing valuable feedback. Therefore this will be one of our last steps in the process. 

**Brew package upgrading**
Sometimes brew changes their default version to a non-BC version of the same software and this generates errors for users of valet-plus. To prevent this we'll need to rewrite some pieces of code that reference brew binaries without a version. E.G: `mysql` is not allowed to exist but `mysql@5.7` is. 

This change is similar to our change with the PHP binaries but less impactful since we won't need an entire brew tap to maintain this. Which by the way is still in progress: https://github.com/weprovide/valet-plus/issues/298

Classes that need refactors:
- [ ] Dnsmasq
- [ ] Elasticsearch
- [ ] Mailhog
- [ ] MySQL
- [ ] Nginx
- [ ] RabbitMQ
- [ ] Redis
- [ ] Varnish

Keep tuned for further updates on the process.

Kind regards,
The valet-plus team
